### ISSUE TITLE
Continuous "Loading..." 

### ISSUE THREAD

**Issue by shxllshock** [MrlolDev/chatgpt-bot#1]
Writing `/chat` along with a message makes the bot stuck in "Loading..."

![image](https://user-images.githubusercontent.com/67878277/206925002-c91dbbc1-63d1-4649-b5bf-7c76dc68c9cb.png)

**Comment by MrlolDev** [comment]
Hello, sorry for the inconvenience this is due we are fixing a bug and we are reloading the bot to fix it. Now it should work better if you find another bug report it with the command /feedback. Thanks for using the bot and sorry for the inconvenience,

**Comment by shxllshock** [comment]
Thank you, it works now.
